const props = {
  cardContainerFont: "",
  cardContainerMargin: "1rem",
  cardContainerPadding: "1rem",
  cardContainerBorder: "",
  cardContainerBorderRadius: ".4rem",
  cardContainerBoxShadow:
    "rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px",
  cardContainerColor: "",
  cardContainerBackgroundColor: "",
  cardContainerWidth: "",
  cardContainerHeight: "",
  cardContainerMinWidth: "",
  cardContainerMinHeight: "",
  cardContainerMaxWidth: "",
  cardContainerMaxHeight: "",
  cardContainerText: "",
  cardContainerGridColumn: "",
  cardContainerGridRow: "",
  cardContainerAlignSelf: "",
  cardContainerTextAlign: "",
  cardContainerDisplayKeys: "some some_not",
  cardContainerDisplay: "grid",
  cardContainerGridTemplateColumns: "1fr 1fr 1fr 1fr",
  cardContainerGridTemplateRows: "1fr 1fr 1.2fr .3fr 1fr 1fr",
  cardContainerGap: "0.5rem .5rem",
  buttonRightFont: "",
  buttonRightMargin: "",
  buttonRightPadding: "",
  buttonRightBorder: ".5px solid #3ABBC7",
  buttonRightBorderRadius: ".5rem",
  buttonRightBoxShadow: "",
  buttonRightColor: "#3ABBC7",
  buttonRightBackgroundColor: "#ffff",
  buttonRightWidth: "",
  buttonRightHeight: "",
  buttonRightText: "Reschedule",
};

export { props };
