const props = {
  cardContainer: {
    font: "",
    margin: "1rem",
    padding: "1rem",
    border: "",
    borderRadius: ".4rem",
    boxShadow:
      "rgba(0, 0, 0, 0.12) 0px 1px 3px, rgba(0, 0, 0, 0.24) 0px 1px 2px",
    color: "",
    backgroundColor: "",
    width: "",
    height: "",
    minWidth: "",
    minHeight: "",
    maxWidth: "",
    maxHeight: "",
    text: "",
    gridColumn: "",
    gridRow: "",
    alignSelf: "",
    textAlign: "",
    displayKeys: "some some_not",
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1fr 1fr",
    gridTemplateRows: "1fr 1fr 1.2fr .3fr 1fr 1fr",
    gap: "0.5rem .5rem",
  },
  buttonRight: {
    font: "",
    margin: "",
    padding: "",
    border: ".5px solid #3ABBC7",
    borderRadius: ".5rem",
    boxShadow: "",
    color: "#3ABBC7",
    backgroundColor: "#ffff",
    width: "",
    height: "",
    text: "Reschedule",
  },
};

export { props };
